// This file is autogenerated. Changes will be overwritten.
#include <UVLADIE3JM/moc_advancedsetupdialog.cpp>
#include <UVLADIE3JM/moc_histview.cpp>
#include <UVLADIE3JM/moc_liveview.cpp>
#include <UVLADIE3JM/moc_mainwindow.cpp>
#include <UVLADIE3JM/moc_settings.cpp>
#include <UVLADIE3JM/moc_stagecontrol.cpp>
