[nautilai]
prefix = 'default_'
auto_contrast_brightness = true
outdir = 'E:\'
ext_analysis = './resources/well_data.exe'
ffmpeg_dir = 'C:\Program Files\ffmpeg\ffmpeg.exe'
xy_pixel_size = 1.0
machine_vars_file_path = 'C:\TODO'

[device.nidaqmx]
device = "Dev2"
device_2 = "DevOR"
num_dig_samples = 10
max_voltage = 1.4
shutter_delay_ms = 1000

[device.photometrics]
trigger_mode = 1792
exposure_mode = 5
speed_table_index = 0

[acquisition]
fps = 10.0
duration = 1.0
led_intensity = 50.0
storage_type = 2
auto_tile = true
encode_video = true
rows = 2
cols = 3
tile_map = [0, 1, 2, 5, 4, 3]

[acquisition.region]
s1 = 1088
p1 = 1088
s2 = 2111
p2 = 2111
sbin = 2
pbin = 2

[acquisition.live_view]
enable_live_view_during_acquisition = true
vflip = false
hflip = true

[device.kinetix.line_read_times]
dynamic_range = 3.75
speed = 0.625
sensitivity = 3.53125
sub_electron = 60.1

[device.tango]
com = "COM3"
step_small = 5
step_medium = 15
step_large = 25
