
[nautilai]
prefix = 'default_'
auto_contrast_brightness = true
outdir = 'E:\'
ext_analysis = './resources/local_analysis.exe'
ffmpeg_dir = 'C:\Program Files\ffmpeg\ffmpeg.exe'


[device]

[device.nidaqmx]
device = "Dev1"
device_2 = "DevOR"
num_dig_samples = 10

[device.photometrics]
trigger_mode = 1792
exposure_mode = 5
speed_table_index = 0

[device.kinetix]

[device.kinetix.line_read_times]
speed = 0.625
dynamic_range = 3.75
sub_electron = 60.1
sensitivity = 3.53125


[device.tango]
step_small = 50
step_medium = 500
step_large = 5000


[acquisition]
rows = 2
fps = 250.0
duration = 30.0
tile_map = [0, 1, 2, 3, 4, 5]
led_intensity = 10.0
encode_video = true
storage_type = 2
auto_tile = true
cols = 3

[acquisition.region]
s1 = 1088
p1 = 1088
s2 = 2111
p2 = 2111


[acquisition.live_view]
enable_live_view_during_acquisition = true


[stage]
location = []
