[stage]
location = [
{ x=102130.0, y=61480.0 },
{ x=66130.0,  y=61380.0 },
{ x=30030.0,  y=61430.0 },
{ x=102080.0, y=25430.0 },
{ x=66030.0,  y=25430.0 },
{ x=30030.0,  y=25430.0 },
]

[roi]
dim = 2
width = 128
height = 128

[wells.A1]
serial_position = 0
is_active = true
grid_position = { row = 0, col = 0 }
center_coordinates = { x_pos = 195.0, y_pos = 193.0 }

[wells.A2]
serial_position = 1
is_active = true
grid_position = { row = 0, col = 1 }
center_coordinates = { x_pos = 406.0, y_pos = 192.0 }

[wells.A3]
serial_position = 2
is_active = true
grid_position = { row = 0, col = 2 }
center_coordinates = { x_pos = 621.0, y_pos = 195.0 }

[wells.A4]
serial_position = 3
is_active = true
grid_position = { row = 0, col = 3 }
center_coordinates = { x_pos = 834.0, y_pos = 197.0 }

[wells.A5]
serial_position = 4
is_active = true
grid_position = { row = 0, col = 4 }
center_coordinates = { x_pos = 1221.0, y_pos = 194.0 }

[wells.A6]
serial_position = 5
is_active = true
grid_position = { row = 0, col = 5 }
center_coordinates = { x_pos = 1432.0, y_pos = 190.0 }

[wells.A7]
serial_position = 6
is_active = true
grid_position = { row = 0, col = 6 }
center_coordinates = { x_pos = 1645.0, y_pos = 192.0 }

[wells.A8]
serial_position = 7
is_active = true
grid_position = { row = 0, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 195.0 }

[wells.A9]
serial_position = 8
is_active = true
grid_position = { row = 0, col = 8 }
center_coordinates = { x_pos = 2240.0, y_pos = 191.0 }

[wells.A10]
serial_position = 9
is_active = true
grid_position = { row = 0, col = 9 }
center_coordinates = { x_pos = 2454.0, y_pos = 190.0 }

[wells.A11]
serial_position = 10
is_active = true
grid_position = { row = 0, col = 10 }
center_coordinates = { x_pos = 2666.0, y_pos = 193.0 }

[wells.A12]
serial_position = 11
is_active = true
grid_position = { row = 0, col = 11 }
center_coordinates = { x_pos = 2879.0, y_pos = 195.0 }

[wells.B1]
serial_position = 12
is_active = true
grid_position = { row = 1, col = 0 }
center_coordinates = { x_pos = 192.0, y_pos = 403.0 }

[wells.B2]
serial_position = 13
is_active = true
grid_position = { row = 1, col = 1 }
center_coordinates = { x_pos = 405.0, y_pos = 405.0 }

[wells.B3]
serial_position = 14
is_active = true
grid_position = { row = 1, col = 2 }
center_coordinates = { x_pos = 619.0, y_pos = 407.0 }

[wells.B4]
serial_position = 15
is_active = true
grid_position = { row = 1, col = 3 }
center_coordinates = { x_pos = 831.0, y_pos = 409.0 }

[wells.B5]
serial_position = 16
is_active = true
grid_position = { row = 1, col = 4 }
center_coordinates = { x_pos = 1216.0, y_pos = 401.0 }

[wells.B6]
serial_position = 17
is_active = true
grid_position = { row = 1, col = 5 }
center_coordinates = { x_pos = 1430.0, y_pos = 403.0 }

[wells.B7]
serial_position = 18
is_active = true
grid_position = { row = 1, col = 6 }
center_coordinates = { x_pos = 1644.0, y_pos = 403.0 }

[wells.B8]
serial_position = 19
is_active = true
grid_position = { row = 1, col = 7 }
center_coordinates = { x_pos = 1857.0, y_pos = 406.0 }

[wells.B9]
serial_position = 20
is_active = true
grid_position = { row = 1, col = 8 }
center_coordinates = { x_pos = 2239.0, y_pos = 403.0 }

[wells.B10]
serial_position = 21
is_active = true
grid_position = { row = 1, col = 9 }
center_coordinates = { x_pos = 2451.0, y_pos = 403.0 }

[wells.B11]
serial_position = 22
is_active = true
grid_position = { row = 1, col = 10 }
center_coordinates = { x_pos = 2666.0, y_pos = 405.0 }

[wells.B12]
serial_position = 23
is_active = true
grid_position = { row = 1, col = 11 }
center_coordinates = { x_pos = 2879.0, y_pos = 406.0 }

[wells.C1]
serial_position = 24
is_active = true
grid_position = { row = 2, col = 0 }
center_coordinates = { x_pos = 189.0, y_pos = 618.0 }

[wells.C2]
serial_position = 25
is_active = true
grid_position = { row = 2, col = 1 }
center_coordinates = { x_pos = 404.0, y_pos = 619.0 }

[wells.C3]
serial_position = 26
is_active = true
grid_position = { row = 2, col = 2 }
center_coordinates = { x_pos = 618.0, y_pos = 620.0 }

[wells.C4]
serial_position = 27
is_active = true
grid_position = { row = 2, col = 3 }
center_coordinates = { x_pos = 830.0, y_pos = 621.0 }

[wells.C5]
serial_position = 28
is_active = true
grid_position = { row = 2, col = 4 }
center_coordinates = { x_pos = 1214.0, y_pos = 615.0 }

[wells.C6]
serial_position = 29
is_active = true
grid_position = { row = 2, col = 5 }
center_coordinates = { x_pos = 1428.0, y_pos = 617.0 }

[wells.C7]
serial_position = 30
is_active = true
grid_position = { row = 2, col = 6 }
center_coordinates = { x_pos = 1643.0, y_pos = 619.0 }

[wells.C8]
serial_position = 31
is_active = true
grid_position = { row = 2, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 619.0 }

[wells.C9]
serial_position = 32
is_active = true
grid_position = { row = 2, col = 8 }
center_coordinates = { x_pos = 2238.0, y_pos = 618.0 }

[wells.C10]
serial_position = 33
is_active = true
grid_position = { row = 2, col = 9 }
center_coordinates = { x_pos = 2450.0, y_pos = 617.0 }

[wells.C11]
serial_position = 34
is_active = true
grid_position = { row = 2, col = 10 }
center_coordinates = { x_pos = 2664.0, y_pos = 619.0 }

[wells.C12]
serial_position = 35
is_active = true
grid_position = { row = 2, col = 11 }
center_coordinates = { x_pos = 2877.0, y_pos = 620.0 }

[wells.D1]
serial_position = 36
is_active = true
grid_position = { row = 3, col = 0 }
center_coordinates = { x_pos = 189.0, y_pos = 830.0 }

[wells.D2]
serial_position = 37
is_active = true
grid_position = { row = 3, col = 1 }
center_coordinates = { x_pos = 404.0, y_pos = 830.0 }

[wells.D3]
serial_position = 38
is_active = true
grid_position = { row = 3, col = 2 }
center_coordinates = { x_pos = 618.0, y_pos = 830.0 }

[wells.D4]
serial_position = 39
is_active = true
grid_position = { row = 3, col = 3 }
center_coordinates = { x_pos = 830.0, y_pos = 830.0 }

[wells.D5]
serial_position = 40
is_active = true
grid_position = { row = 3, col = 4 }
center_coordinates = { x_pos = 1214.0, y_pos = 830.0 }

[wells.D6]
serial_position = 41
is_active = true
grid_position = { row = 3, col = 5 }
center_coordinates = { x_pos = 1428.0, y_pos = 830.0 }

[wells.D7]
serial_position = 42
is_active = true
grid_position = { row = 3, col = 6 }
center_coordinates = { x_pos = 1643.0, y_pos = 830.0 }

[wells.D8]
serial_position = 43
is_active = true
grid_position = { row = 3, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 830.0 }

[wells.D9]
serial_position = 44
is_active = true
grid_position = { row = 3, col = 8 }
center_coordinates = { x_pos = 2238.0, y_pos = 830.0 }

[wells.D10]
serial_position = 45
is_active = true
grid_position = { row = 3, col = 9 }
center_coordinates = { x_pos = 2450.0, y_pos = 830.0 }

[wells.D11]
serial_position = 46
is_active = true
grid_position = { row = 3, col = 10 }
center_coordinates = { x_pos = 2664.0, y_pos = 830.0 }

[wells.D12]
serial_position = 47
is_active = true
grid_position = { row = 3, col = 11 }
center_coordinates = { x_pos = 2877.0, y_pos = 830.0 }

[wells.E1]
serial_position = 48
is_active = true
grid_position = { row = 4, col = 0 }
center_coordinates = { x_pos = 189.0, y_pos = 1217.0 }

[wells.E2]
serial_position = 49
is_active = true
grid_position = { row = 4, col = 1 }
center_coordinates = { x_pos = 404.0, y_pos = 1217.0 }

[wells.E3]
serial_position = 50
is_active = true
grid_position = { row = 4, col = 2 }
center_coordinates = { x_pos = 618.0, y_pos = 1217.0 }

[wells.E4]
serial_position = 51
is_active = true
grid_position = { row = 4, col = 3 }
center_coordinates = { x_pos = 830.0, y_pos = 1217.0 }

[wells.E5]
serial_position = 52
is_active = true
grid_position = { row = 4, col = 4 }
center_coordinates = { x_pos = 1214.0, y_pos = 1217.0 }

[wells.E6]
serial_position = 53
is_active = true
grid_position = { row = 4, col = 5 }
center_coordinates = { x_pos = 1428.0, y_pos = 1217.0 }

[wells.E7]
serial_position = 54
is_active = true
grid_position = { row = 4, col = 6 }
center_coordinates = { x_pos = 1643.0, y_pos = 1217.0 }

[wells.E8]
serial_position = 55
is_active = true
grid_position = { row = 4, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 1217.0 }

[wells.E9]
serial_position = 56
is_active = true
grid_position = { row = 4, col = 8 }
center_coordinates = { x_pos = 2238.0, y_pos = 1217.0 }

[wells.E10]
serial_position = 57
is_active = true
grid_position = { row = 4, col = 9 }
center_coordinates = { x_pos = 2450.0, y_pos = 1217.0 }

[wells.E11]
serial_position = 58
is_active = true
grid_position = { row = 4, col = 10 }
center_coordinates = { x_pos = 2664.0, y_pos = 1217.0 }

[wells.E12]
serial_position = 59
is_active = true
grid_position = { row = 4, col = 11 }
center_coordinates = { x_pos = 2877.0, y_pos = 1217.0 }

[wells.F1]
serial_position = 60
is_active = true
grid_position = { row = 5, col = 0 }
center_coordinates = { x_pos = 189.0, y_pos = 1429.0 }

[wells.F2]
serial_position = 61
is_active = true
grid_position = { row = 5, col = 1 }
center_coordinates = { x_pos = 404.0, y_pos = 1429.0 }

[wells.F3]
serial_position = 62
is_active = true
grid_position = { row = 5, col = 2 }
center_coordinates = { x_pos = 618.0, y_pos = 1429.0 }

[wells.F4]
serial_position = 63
is_active = true
grid_position = { row = 5, col = 3 }
center_coordinates = { x_pos = 830.0, y_pos = 1429.0 }

[wells.F5]
serial_position = 64
is_active = true
grid_position = { row = 5, col = 4 }
center_coordinates = { x_pos = 1214.0, y_pos = 1429.0 }

[wells.F6]
serial_position = 65
is_active = true
grid_position = { row = 5, col = 5 }
center_coordinates = { x_pos = 1428.0, y_pos = 1429.0 }

[wells.F7]
serial_position = 66
is_active = true
grid_position = { row = 5, col = 6 }
center_coordinates = { x_pos = 1643.0, y_pos = 1429.0 }

[wells.F8]
serial_position = 67
is_active = true
grid_position = { row = 5, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 1429.0 }

[wells.F9]
serial_position = 68
is_active = true
grid_position = { row = 5, col = 8 }
center_coordinates = { x_pos = 2238.0, y_pos = 1429.0 }

[wells.F10]
serial_position = 69
is_active = true
grid_position = { row = 5, col = 9 }
center_coordinates = { x_pos = 2450.0, y_pos = 1429.0 }

[wells.F11]
serial_position = 70
is_active = true
grid_position = { row = 5, col = 10 }
center_coordinates = { x_pos = 2664.0, y_pos = 1429.0 }

[wells.F12]
serial_position = 71
is_active = true
grid_position = { row = 5, col = 11 }
center_coordinates = { x_pos = 2877.0, y_pos = 1429.0 }

[wells.G1]
serial_position = 72
is_active = true
grid_position = { row = 6, col = 0 }
center_coordinates = { x_pos = 189.0, y_pos = 1642.0 }

[wells.G2]
serial_position = 73
is_active = true
grid_position = { row = 6, col = 1 }
center_coordinates = { x_pos = 404.0, y_pos = 1642.0 }

[wells.G3]
serial_position = 74
is_active = true
grid_position = { row = 6, col = 2 }
center_coordinates = { x_pos = 618.0, y_pos = 1642.0 }

[wells.G4]
serial_position = 75
is_active = true
grid_position = { row = 6, col = 3 }
center_coordinates = { x_pos = 830.0, y_pos = 1642.0 }

[wells.G5]
serial_position = 76
is_active = true
grid_position = { row = 6, col = 4 }
center_coordinates = { x_pos = 1214.0, y_pos = 1642.0 }

[wells.G6]
serial_position = 77
is_active = true
grid_position = { row = 6, col = 5 }
center_coordinates = { x_pos = 1428.0, y_pos = 1642.0 }

[wells.G7]
serial_position = 78
is_active = true
grid_position = { row = 6, col = 6 }
center_coordinates = { x_pos = 1643.0, y_pos = 1642.0 }

[wells.G8]
serial_position = 79
is_active = true
grid_position = { row = 6, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 1642.0 }

[wells.G9]
serial_position = 80
is_active = true
grid_position = { row = 6, col = 8 }
center_coordinates = { x_pos = 2238.0, y_pos = 1642.0 }

[wells.G10]
serial_position = 81
is_active = true
grid_position = { row = 6, col = 9 }
center_coordinates = { x_pos = 2450.0, y_pos = 1642.0 }

[wells.G11]
serial_position = 82
is_active = true
grid_position = { row = 6, col = 10 }
center_coordinates = { x_pos = 2664.0, y_pos = 1642.0 }

[wells.G12]
serial_position = 83
is_active = true
grid_position = { row = 6, col = 11 }
center_coordinates = { x_pos = 2877.0, y_pos = 1642.0 }

[wells.H1]
serial_position = 84
is_active = true
grid_position = { row = 7, col = 0 }
center_coordinates = { x_pos = 189.0, y_pos = 1854.0 }

[wells.H2]
serial_position = 85
is_active = true
grid_position = { row = 7, col = 1 }
center_coordinates = { x_pos = 404.0, y_pos = 1854.0 }

[wells.H3]
serial_position = 86
is_active = true
grid_position = { row = 7, col = 2 }
center_coordinates = { x_pos = 618.0, y_pos = 1854.0 }

[wells.H4]
serial_position = 87
is_active = true
grid_position = { row = 7, col = 3 }
center_coordinates = { x_pos = 830.0, y_pos = 1854.0 }

[wells.H5]
serial_position = 88
is_active = true
grid_position = { row = 7, col = 4 }
center_coordinates = { x_pos = 1214.0, y_pos = 1854.0 }

[wells.H6]
serial_position = 89
is_active = true
grid_position = { row = 7, col = 5 }
center_coordinates = { x_pos = 1428.0, y_pos = 1854.0 }

[wells.H7]
serial_position = 90
is_active = true
grid_position = { row = 7, col = 6 }
center_coordinates = { x_pos = 1643.0, y_pos = 1854.0 }

[wells.H8]
serial_position = 91
is_active = true
grid_position = { row = 7, col = 7 }
center_coordinates = { x_pos = 1855.0, y_pos = 1854.0 }

[wells.H9]
serial_position = 92
is_active = true
grid_position = { row = 7, col = 8 }
center_coordinates = { x_pos = 2238.0, y_pos = 1854.0 }

[wells.H10]
serial_position = 93
is_active = true
grid_position = { row = 7, col = 9 }
center_coordinates = { x_pos = 2450.0, y_pos = 1854.0 }

[wells.H11]
serial_position = 94
is_active = true
grid_position = { row = 7, col = 10 }
center_coordinates = { x_pos = 2664.0, y_pos = 1854.0 }

[wells.H12]
serial_position = 95
is_active = true
grid_position = { row = 7, col = 11 }
center_coordinates = { x_pos = 2877.0, y_pos = 1854.0 }


