[stage]

# TODO set these to the actual center of the plate
x0_ref = 102130.0
y0_ref = 61480.0

num_wells = 96
roi_size_x = 64
roi_size_y = 64
num_wells_h = 4
num_wells_v = 4
well_spacing = 9000
h_offset = 0
v_offset = 0
