[stage]
location = [
    { x = 102130.0, y = 61480.0 },
    { x = 66130.0, y = 61380.0 },
    { x = 30030.0, y = 61430.0 },
    { x = 102080.0, y = 25430.0 },
    { x = 66030.0, y = 25430.0 },
    { x = 30030.0, y = 25430.0 },
]

num_wells = 96
roi_size_x = 64
roi_size_y = 64
num_wells_h = 4
num_wells_v = 4
well_spacing = 9000
h_offset = 0
v_offset = 0
