[stage]

# TODO set these to the actual center of the plate
y0_ref = 43080.0
x0_ref = 65800.0

num_wells = 24
roi_size_x = 256
roi_size_y = 128
num_wells_h = 2
num_wells_v = 2
well_spacing = 18000
h_offset = 0
v_offset = 0
