[stage]
location = [
    { x = 104980.0, y = 62580.0 },
    { x = 65880.0, y = 62850.0 },
    { x = 26630.0, y = 62580.0 },
    { x = 104830.0, y = 23580.0 },
    { x = 65730.0, y = 23580.0 },
    { x = 26680.0, y = 23580.0 },
]

num_wells = 24
roi_size_x = 256
roi_size_y = 128
num_wells_h = 2
num_wells_v = 2
well_spacing = 18000
h_offset = 0
v_offset = 0
