name: Build Local Analysis Executable

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.3

    - name: Compile Executable
      run: |
        cd src/local_analysis
        pip install -r src/requirements-dev.txt
        pip install -r src/requirements.txt
        pyinstaller -i app/icon/logo.ico -F src/local_analysis.py

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: local_analysis
        path: src/local_analysis/dist/*
